development:
  host: localhost
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_react_rails_dev
  pool: 5
  username: root
  password: root123

test:
  host: localhost
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_react_rails_test
  pool: 5
  username: root
  password: root123
  
production:
  host: localhost
  adapter: mysql2
  encoding: utf8
  reconnect: false 
  database: test_react_rails
  pool: 5
  username: root
  password: root123
